import { Employee } from './db';

interface PayrollData {
  employee: Employee;
  hours: number;
  workDays?: number;
  hourlyWage?: number;
  transportAllowance?: number;
  salary: number;
}

// 生成月度工资报告 Markdown
export const generatePayrollMarkdown = (
  payrollData: PayrollData[],
  year: number,
  month: number,
  language: 'zh' | 'ja' | 'en' = 'zh'
): string => {
  const localeMap: { [key: string]: string } = {
    'zh': 'zh-CN',
    'ja': 'ja-JP',
    'en': 'en-US',
  };
  const locale = localeMap[language] || 'zh-CN';
  
  const texts = {
    zh: {
      title: '月度工资报告',
      reportMonth: '报告月份',
      generatedDate: '生成日期',
      noData: '本月无员工工资数据',
      summary: '汇总信息',
      item: '项目',
      value: '数值',
      employeeCount: '员工人数',
      people: '人',
      totalHours: '总工时',
      hours: '小时',
      totalSalary: '总工资',
      avgSalary: '平均工资',
      detailedTable: '详细工资表',
      name: '姓名',
      position: '职位',
      hourlyRate: '时薪',
      workHours: '工作时数',
      workDays: '工作天数',
      hourlyWage: '时薪工资',
      transportFee: '交通费',
      grossPay: '应发工资',
      remarks: '备注',
      noAttendance: '无考勤',
      partTime: '兼职',
      overtime: '加班多',
      positionStats: '职位分组统计',
      count: '人数',
      employeeList: '员工列表',
      ranking: '工资排行',
      salaryRanking: '工资排行 TOP 5',
      hoursRanking: '工时排行 TOP 5',
      notesSection: '备注说明',
      calcMethod: '工资计算方式',
      calcFormula: '应发工资 = 工作时数 × 时薪',
      attendancePeriod: '考勤统计周期',
      statsPeriod: '统计周期',
      hoursSource: '工时来源',
      hoursSourceText: '考勤打卡记录',
      salaryStandard: '工资标准',
      salaryStandardText: '员工档案中的时薪',
      notices: '注意事项',
      notice1: '本报告为初步统计，实际发放时请核对考勤记录',
      notice2: '未包含扣款、奖金、补贴等项目',
      notice3: '如有疑问，请核对考勤明细',
      notice4: '工资发放前请员工确认签字',
      autoGenerated: '由咖啡店管理系统自动生成',
      yearSuffix: '年',
      monthSuffix: '月',
      daySuffix: '日',
      currency: '¥',
    },
    ja: {
      title: '月次給与レポート',
      reportMonth: 'レポート月',
      generatedDate: '生成日',
      noData: '今月の従業員給与データなし',
      summary: 'サマリー情報',
      item: '項目',
      value: '数値',
      employeeCount: '従業員数',
      people: '名',
      totalHours: '総労働時間',
      hours: '時間',
      totalSalary: '総給与',
      avgSalary: '平均給与',
      detailedTable: '詳細給与表',
      name: '氏名',
      position: '役職',
      hourlyRate: '時給',
      workHours: '労働時間',
      workDays: '勤務日数',
      hourlyWage: '時給賃金',
      transportFee: '交通費',
      grossPay: '支給額',
      remarks: '備考',
      noAttendance: '勤怠なし',
      partTime: 'アルバイト',
      overtime: '残業多',
      positionStats: '役職別統計',
      count: '人数',
      employeeList: '従業員リスト',
      ranking: '給与ランキング',
      salaryRanking: '給与ランキング TOP 5',
      hoursRanking: '労働時間ランキング TOP 5',
      notesSection: '備考説明',
      calcMethod: '給与計算方法',
      calcFormula: '支給額 = 労働時間 × 時給',
      attendancePeriod: '勤怠集計期間',
      statsPeriod: '集計期間',
      hoursSource: '労働時間ソース',
      hoursSourceText: '勤怠打刻記録',
      salaryStandard: '給与基準',
      salaryStandardText: '従業員ファイルの時給',
      notices: '注意事項',
      notice1: '本レポートは初期統計です。実際の支給時には勤怠記録を確認してください',
      notice2: '控除、ボーナス、手当などの項目は含まれていません',
      notice3: '疑問がある場合は、勤怠明細を確認してください',
      notice4: '給与支給前に従業員の確認とサインを取得してください',
      autoGenerated: 'カフェ管理システムにより自動生成',
      yearSuffix: '年',
      monthSuffix: '月',
      daySuffix: '日',
      currency: '¥',
    },
    en: {
      title: 'Monthly Payroll Report',
      reportMonth: 'Report Month',
      generatedDate: 'Generated Date',
      noData: 'No employee payroll data this month',
      summary: 'Summary',
      item: 'Item',
      value: 'Value',
      employeeCount: 'Employee Count',
      people: '',
      totalHours: 'Total Hours',
      hours: 'hours',
      totalSalary: 'Total Salary',
      avgSalary: 'Average Salary',
      detailedTable: 'Detailed Payroll',
      name: 'Name',
      position: 'Position',
      hourlyRate: 'Hourly Rate',
      workHours: 'Work Hours',
      workDays: 'Work Days',
      hourlyWage: 'Hourly Wage',
      transportFee: 'Transport Fee',
      grossPay: 'Gross Pay',
      remarks: 'Remarks',
      noAttendance: 'No attendance',
      partTime: 'Part-time',
      overtime: 'Overtime',
      positionStats: 'Position Statistics',
      count: 'Count',
      employeeList: 'Employee List',
      ranking: 'Salary Ranking',
      salaryRanking: 'Salary Ranking TOP 5',
      hoursRanking: 'Hours Ranking TOP 5',
      notesSection: 'Notes',
      calcMethod: 'Calculation Method',
      calcFormula: 'Gross Pay = Work Hours × Hourly Rate',
      attendancePeriod: 'Attendance Period',
      statsPeriod: 'Statistics Period',
      hoursSource: 'Hours Source',
      hoursSourceText: 'Attendance clock-in records',
      salaryStandard: 'Salary Standard',
      salaryStandardText: 'Hourly rate from employee profile',
      notices: 'Important Notes',
      notice1: 'This is a preliminary report. Please verify attendance records before final payment',
      notice2: 'Does not include deductions, bonuses, or allowances',
      notice3: 'If you have questions, please review attendance details',
      notice4: 'Please obtain employee confirmation and signature before payment',
      autoGenerated: 'Auto-generated by Coffee Shop Management System',
      yearSuffix: '/',
      monthSuffix: '',
      daySuffix: '',
      currency: '$',
    },
  };

  const text = texts[language] || texts.zh;
  const monthStr = `${year}${text.yearSuffix}${month}${text.monthSuffix}`;
  
  let markdown = `# 💰 ${text.title}\n\n`;
  markdown += `📅 **${text.reportMonth}**: ${monthStr}\n`;
  markdown += `📝 **${text.generatedDate}**: ${new Date().toLocaleDateString(locale, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    weekday: 'long',
  })}\n\n`;
  markdown += `---\n\n`;

  if (payrollData.length === 0) {
    markdown += `⚠️ **${text.noData}**\n`;
    return markdown;
  }

  // 计算总计
  const totalHours = payrollData.reduce((sum, item) => sum + item.hours, 0);
  const totalSalary = payrollData.reduce((sum, item) => sum + item.salary, 0);

  // 汇总信息
  markdown += `## 📊 ${text.summary}\n\n`;
  markdown += `| ${text.item} | ${text.value} |\n`;
  markdown += `|------|------|\n`;
  markdown += `| 👥 ${text.employeeCount} | **${payrollData.length}** ${text.people} |\n`;
  markdown += `| ⏰ ${text.totalHours} | **${totalHours.toFixed(2)}** ${text.hours} |\n`;
  markdown += `| 💵 ${text.totalSalary} | **${text.currency}${totalSalary.toFixed(2)}** |\n`;
  markdown += `| 📈 ${text.avgSalary} | **${text.currency}${(totalSalary / payrollData.length).toFixed(2)}** |\n`;
  markdown += `\n---\n\n`;

  // 详细工资表
  markdown += `## 📋 ${text.detailedTable}\n\n`;
  markdown += `| ${text.name} | ${text.position} | ${text.hourlyRate} | ${text.workHours} | ${text.workDays} | ${text.hourlyWage} | ${text.transportFee} | ${text.grossPay} | ${text.remarks} |\n`;
  markdown += `|------|------|------|----------|----------|----------|--------|----------|------|\n`;

  payrollData.forEach(item => {
    const { employee, hours, workDays = 0, hourlyWage = 0, transportAllowance = 0, salary } = item;
    const positionEmoji = getPositionEmoji(employee.position);
    markdown += `| ${positionEmoji} ${employee.name} | ${employee.position} | ${text.currency}${employee.hourlyRate.toFixed(2)} | ${hours.toFixed(2)}h | ${workDays}${text.daySuffix} | ${text.currency}${hourlyWage.toFixed(2)} | ${text.currency}${transportAllowance.toFixed(2)} | **${text.currency}${salary.toFixed(2)}** | `;
    
    // 添加备注
    if (hours === 0) {
      markdown += `⚠️ ${text.noAttendance} `;
    } else if (hours < 40) {
      markdown += `📌 ${text.partTime} `;
    } else if (hours > 200) {
      markdown += `🔥 ${text.overtime} `;
    }
    
    markdown += `|\n`;
  });

  markdown += `\n---\n\n`;

  // 按职位分组统计
  markdown += `## 📈 ${text.positionStats}\n\n`;
  const positionGroups = groupByPosition(payrollData);
  
  Object.entries(positionGroups).forEach(([position, items]) => {
    const positionHours = items.reduce((sum, item) => sum + item.hours, 0);
    const positionSalary = items.reduce((sum, item) => sum + item.salary, 0);
    const emoji = getPositionEmoji(position);
    
    markdown += `### ${emoji} ${position}\n\n`;
    markdown += `- 👥 ${text.count}: **${items.length}** ${text.people}\n`;
    markdown += `- ⏰ ${text.totalHours}: **${positionHours.toFixed(2)}** ${text.hours}\n`;
    markdown += `- 💰 ${text.totalSalary}: **${text.currency}${positionSalary.toFixed(2)}**\n`;
    markdown += `- 📊 ${text.avgSalary}: **${text.currency}${(positionSalary / items.length).toFixed(2)}**\n\n`;
    
    markdown += `**${text.employeeList}:**\n\n`;
    items.forEach(item => {
      markdown += `- ${item.employee.name}: ${item.hours.toFixed(2)}h × ${text.currency}${item.employee.hourlyRate} = ${text.currency}${item.salary.toFixed(2)}\n`;
    });
    markdown += `\n`;
  });

  markdown += `---\n\n`;

  // 工资排行
  markdown += `## 🏆 ${text.ranking}\n\n`;
  const sortedBysalary = [...payrollData].sort((a, b) => b.salary - a.salary);
  
  markdown += `### 💎 ${text.salaryRanking}\n\n`;
  sortedBysalary.slice(0, 5).forEach((item, index) => {
    const medal = ['🥇', '🥈', '🥉', '4️⃣', '5️⃣'][index];
    markdown += `${medal} **${item.employee.name}** (${item.employee.position}): ${text.currency}${item.salary.toFixed(2)}\n`;
  });
  markdown += `\n`;

  // 工时排行
  markdown += `### ⏰ ${text.hoursRanking}\n\n`;
  const sortedByHours = [...payrollData].sort((a, b) => b.hours - a.hours);
  sortedByHours.slice(0, 5).forEach((item, index) => {
    const medal = ['🥇', '🥈', '🥉', '4️⃣', '5️⃣'][index];
    markdown += `${medal} **${item.employee.name}**: ${item.hours.toFixed(2)} ${text.hours}\n`;
  });
  markdown += `\n`;

  markdown += `---\n\n`;

  // 备注说明
  markdown += `## 📝 ${text.notesSection}\n\n`;
  markdown += `### ${text.calcMethod}\n\n`;
  markdown += `\`\`\`\n`;
  markdown += `${text.calcFormula}\n`;
  markdown += `\`\`\`\n\n`;
  markdown += `### ${text.attendancePeriod}\n\n`;
  const lastDay = month === 12 ? '31' : new Date(year, month, 0).getDate();
  markdown += `- 📅 ${text.statsPeriod}: ${monthStr}（1${text.daySuffix} 00:00 ~ ${lastDay}${text.daySuffix} 23:59）\n`;
  markdown += `- ⏰ ${text.hoursSource}: ${text.hoursSourceText}\n`;
  markdown += `- 💵 ${text.salaryStandard}: ${text.salaryStandardText}\n\n`;

  markdown += `### ${text.notices}\n\n`;
  markdown += `- ⚠️ ${text.notice1}\n`;
  markdown += `- 📌 ${text.notice2}\n`;
  markdown += `- 🔍 ${text.notice3}\n`;
  markdown += `- ✅ ${text.notice4}\n\n`;

  markdown += `---\n\n`;
  markdown += `*${text.autoGenerated}*\n`;

  return markdown;
};

// 按职位分组
const groupByPosition = (payrollData: PayrollData[]): { [key: string]: PayrollData[] } => {
  return payrollData.reduce((groups, item) => {
    const position = item.employee.position;
    if (!groups[position]) {
      groups[position] = [];
    }
    groups[position].push(item);
    return groups;
  }, {} as { [key: string]: PayrollData[] });
};

// 获取职位对应的 emoji
const getPositionEmoji = (position: string): string => {
  const emojiMap: { [key: string]: string } = {
    // English keys
    'manager': '👔',
    'barista': '☕️',
    'partTime': '⏰',
    'intern': '📚',
    // Legacy Chinese keys for backward compatibility
    '店长': '👔',
    '咖啡师': '☕️',
    '兼职': '⏰',
    '实习生': '📚',
    '收银员': '💳',
    '清洁工': '🧹',
  };
  return emojiMap[position] || '👤';
};

// 下载 Markdown 文件
export const downloadMarkdownFile = (content: string, filename?: string) => {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `payroll-${new Date().toISOString().slice(0, 7)}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// 一键生成并下载工资报告
export const generateAndDownloadPayroll = async (
  payrollData: PayrollData[],
  year: number,
  month: number,
  language: 'zh' | 'ja' | 'en' = 'zh'
) => {
  const markdown = generatePayrollMarkdown(payrollData, year, month, language);
  const filename = `payroll-${year}-${String(month).padStart(2, '0')}.md`;
  downloadMarkdownFile(markdown, filename);
};




