import { InventoryItem } from './db';

// 生成 Markdown 格式的采购清单
export const generatePurchaseListMarkdown = (lowStockItems: InventoryItem[], language: 'zh' | 'ja' | 'en' = 'zh'): string => {
  const today = new Date();
  const localeMap: { [key: string]: string } = {
    'zh': 'zh-CN',
    'ja': 'ja-JP',
    'en': 'en-US',
  };
  const locale = localeMap[language] || 'zh-CN';
  
  const dateStr = today.toLocaleDateString(locale, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    weekday: 'long',
  });

  const texts = {
    zh: {
      title: '每周采购清单',
      generatedDate: '生成日期',
      noNeed: '库存充足，本周无需采购！',
      needRestock: '需要补充的商品',
      belowThreshold: '以下商品库存已低于阈值，请及时采购',
      productName: '商品名称',
      currentStock: '当前库存',
      unit: '单位',
      safetyStock: '安全库存',
      suggestedQty: '建议采购量',
      category: '类别',
      summary: '采购汇总',
      itemsNeed: '需采购商品数量',
      items: '项',
      lowStock: '低库存警告',
      categorySummary: '分类汇总',
      current: '当前',
      notes: '备注',
      completeThisWeek: '请在本周内完成采购',
      contactSupplier: '如有问题，请联系供应商',
      updateSystem: '采购完成后，请及时更新库存系统',
      autoGenerated: '由咖啡店管理系统自动生成',
    },
    ja: {
      title: '週次購入リスト',
      generatedDate: '生成日',
      noNeed: '在庫十分、今週の購入不要！',
      needRestock: '補充が必要な商品',
      belowThreshold: '以下の商品は在庫が閾値を下回っています。速やかに購入してください',
      productName: '商品名',
      currentStock: '現在在庫',
      unit: '単位',
      safetyStock: '安全在庫',
      suggestedQty: '推奨購入量',
      category: 'カテゴリー',
      summary: '購入サマリー',
      itemsNeed: '購入必要商品数',
      items: '件',
      lowStock: '在庫不足警告',
      categorySummary: 'カテゴリー別サマリー',
      current: '現在',
      notes: '備考',
      completeThisWeek: '今週中に購入を完了してください',
      contactSupplier: '問題がある場合はサプライヤーに連絡してください',
      updateSystem: '購入完了後、速やかに在庫システムを更新してください',
      autoGenerated: 'カフェ管理システムにより自動生成',
    },
    en: {
      title: 'Weekly Purchase List',
      generatedDate: 'Generated Date',
      noNeed: 'All items in stock, no purchase needed this week!',
      needRestock: 'Items Need Restocking',
      belowThreshold: 'The following items are below threshold, please purchase promptly',
      productName: 'Product Name',
      currentStock: 'Current Stock',
      unit: 'Unit',
      safetyStock: 'Safety Stock',
      suggestedQty: 'Suggested Qty',
      category: 'Category',
      summary: 'Purchase Summary',
      itemsNeed: 'Items to Purchase',
      items: 'items',
      lowStock: 'Low Stock Warning',
      categorySummary: 'Category Summary',
      current: 'Current',
      notes: 'Notes',
      completeThisWeek: 'Please complete purchase within this week',
      contactSupplier: 'Contact supplier if any questions',
      updateSystem: 'Update inventory system after purchase',
      autoGenerated: 'Auto-generated by Coffee Shop Management System',
    },
  };

  const text = texts[language] || texts.zh;

  let markdown = `# ☕️ ${text.title}\n\n`;
  markdown += `📅 **${text.generatedDate}**: ${dateStr}\n\n`;
  markdown += `---\n\n`;

  if (lowStockItems.length === 0) {
    markdown += `✅ **${text.noNeed}**\n`;
    return markdown;
  }

  markdown += `## 📦 ${text.needRestock}\n\n`;
  markdown += `> ${text.belowThreshold}\n\n`;
  markdown += `| ${text.productName} | ${text.currentStock} | ${text.unit} | ${text.safetyStock} | ${text.suggestedQty} | ${text.category} |\n`;
  markdown += `|---------|---------|------|---------|-----------|------|\n`;

  let totalItems = 0;

  lowStockItems.forEach(item => {
    const suggestedQuantity = Math.max(item.threshold * 2 - item.quantity, item.threshold);
    const emoji = getCategoryEmoji(item.category);
    markdown += `| ${emoji} ${item.name} | ${item.quantity} | ${item.unit} | ${item.threshold} | **${suggestedQuantity}** | ${item.category} |\n`;
    totalItems++;
  });

  markdown += `\n---\n\n`;
  markdown += `## 📊 ${text.summary}\n\n`;
  markdown += `- 📌 ${text.itemsNeed}: **${totalItems}** ${text.items}\n`;
  markdown += `- 🔴 ${text.lowStock}: **${lowStockItems.length}** ${text.items}\n\n`;

  // 按类别分组
  const categories = [...new Set(lowStockItems.map(item => item.category))];
  markdown += `## 📋 ${text.categorySummary}\n\n`;
  categories.forEach(category => {
    const items = lowStockItems.filter(item => item.category === category);
    const emoji = getCategoryEmoji(category);
    markdown += `### ${emoji} ${category} (${items.length} ${text.items})\n\n`;
    items.forEach(item => {
      markdown += `- [ ] ${item.name} - ${text.current}: ${item.quantity}${item.unit}\n`;
    });
    markdown += `\n`;
  });

  markdown += `---\n\n`;
  markdown += `## 📝 ${text.notes}\n\n`;
  markdown += `- ⏰ ${text.completeThisWeek}\n`;
  markdown += `- 📞 ${text.contactSupplier}\n`;
  markdown += `- ✅ ${text.updateSystem}\n\n`;
  markdown += `---\n\n`;
  markdown += `*${text.autoGenerated}*\n`;

  return markdown;
};

// 根据类别返回对应的 emoji
const getCategoryEmoji = (category: string): string => {
  const emojiMap: { [key: string]: string } = {
    'produce': '🥬',
    'dairy': '🥛',
    'bakery': '🍰',
    'sauce': '🫙',
    'beverage': '🥤',
    'ingredients': '🌱',
    'supplies': '📦',
    'other': '📌',
  };
  return emojiMap[category] || '📌';
};

// 下载 Markdown 文件
export const downloadMarkdownFile = (content: string, filename?: string) => {
  const today = new Date();
  const dateStr = today.toISOString().split('T')[0]; // YYYY-MM-DD
  const finalFilename = filename || `weekly-purchase-${dateStr}.md`;

  // 创建 Blob
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  
  // 创建下载链接
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = finalFilename;
  
  // 触发下载
  document.body.appendChild(link);
  link.click();
  
  // 清理
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// 一键生成并下载采购清单
export const generateAndDownloadPurchaseList = async (lowStockItems: InventoryItem[], language: 'zh' | 'ja' | 'en' = 'zh') => {
  const markdown = generatePurchaseListMarkdown(lowStockItems, language);
  downloadMarkdownFile(markdown);
};


